### ISSUE TITLE
Move License to MIT

### ISSUE THREAD

**Issue by rguliev** [r-hyperspec/unmixR#36]
- [x]  @rguliev contributes MIT as that's decision of Image-IN
- [x]  @cbeleites agrees to contribute under MIT
- [x]  @bryanhanson agrees to contribute under MIT
- [x]  @AaBelov Anton Belov's GSoC Code
- [x]  Conor McManus' GSoC Code

**Comment by Chathurga** [comment]
Conor McManus here, yep I'm okay with this :+1:

**Comment by AaBelov** [comment]
I'm Anton Belov. I'm ok with it.
